### ISSUE TITLE
Also interested in Go based pacemaker_exporter

### ISSUE THREAD

**Issue by akurz** [mjtrangoni/pacemaker_exporter#1]
Hi,

I read you are planning to port the Python pacemaker_exporter to Go. Great :-) ... I'd also be interested to be able to deploy a single binary. If you need testers, I'm in!

Cheers,
Andreas

**Comment by mjtrangoni** [comment]
Hi @akurz,
Could you please test this? What another metrics would you like to have?

Thanks!

**Comment by akurz** [comment]
Hi,

had a look at the metrics and this already looks great ... thanks for your efforts! One metric that would be really useful for us would be to know the number of migration/ban constraints.

Cheers,
Andreas

**Comment by mjtrangoni** [comment]
Hi @akurz,

Thanks for having a look at it. Would you mind sharing with me some `crm_mon -X` anonymized outputs I could work with? Please feel free to mail me directly or just uploading it to gist.

Best regards,
Mario
